# Generated by Django 5.0 on 2023-12-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_addeducation_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='default_profile_picture.png', upload_to='profile_picture'),
        ),
    ]
