# Generated by Django 5.0 on 2023-12-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_photo_userprofile_picture'),
        ('blog', '0002_comments_author_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dislike',
            field=models.ManyToManyField(related_name='post_dislike', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.ManyToManyField(related_name='post_like', to='accounts.userprofile'),
        ),
    ]
