# Generated by Django 5.0 on 2023-12-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_posts_dislike_alter_posts_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='is_validate',
            field=models.BooleanField(null=True),
        ),
    ]
