# Generated by Django 5.0 on 2023-12-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comments_is_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='is_validate',
            field=models.BooleanField(default=False),
        ),
    ]
